version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'data'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'hewrhuqewewrewr'
      MYSQL_ROOT_PASSWORD: 'A4432468432456432432'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - pdg_db:/var/lib/mysql

  backend:
    image: cuc-24/backend
    build:
      dockerfile: backend/Dockerfile

volumes:
  pdg_db:
