CREATE TABLE Users (
  UUID VARCHAR(255) NOT NULL,
  USERNAME VARCHAR(255) UNIQUE NOT NULL,
  EMAIL VARCHAR(255) UNIQUE NOT NULL,
  PASSWORD VARCHAR(4000) NOT NULL,
  VERIFIED INT NOT NULL,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE Posts (
  PID INT AUTO_INCREMENT PRIMARY KEY,
  HEADING VARCHAR(2000),
  CONTENT VARCHAR(10000) NOT NULL,
  PICTURE_URL VARCHAR(255),
  TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY_UUID VARCHAR(255) NOT NULL
)
