CREATE TABLE Users (
  UUID VARCHAR(255) NOT NULL,
  USERNAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  VERIFIED INT NOT NULL
)

CREATE TABLE Posts (
  PID INT AUTO_INCREMENT PRIMARY KEY,
  HEADING VARCHAR(2000),
  CONTENT VARCHAR(10000) NOT NULL,
  PICTURE_URL VAR(255)
)
